name: Login Docker Build

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  login-container:
    uses: ./.github/workflows/login-container.yml
    permissions:
      packages: write
      id-token: write
    with:
      login_build_image_name: "ghcr.io/zitadel/zitadel-login"
      node_version: "20"
